### ISSUE TITLE
Add support for multiple stages

### ISSUE THREAD

**Issue by pbros** [ziebelje/beestat-issues#30]
Hello, 

I would like to request that the Aux (or Cool) stages be visible in the charts, like they are on the official ecobee website.

Thank you

**Comment by ziebelje** [comment]
This is actually already handled, but there may be an issue with the data ecobee is sending to beestat (see issue #6). I'll take a closer look though to see if this is something unrelated.

Example of it working:

![image](https://user-images.githubusercontent.com/3288812/41040740-420ecd64-696b-11e8-9dbf-79c9348a2b63.png)

**Comment by pbros** [comment]
Thanks. In my case it is indeed only showing Aux.

**Comment by ziebelje** [comment]
Hey @pbros, I think I've figured out the cause of this problem with ecobee. Would you mind to verify the type of HVAC system you have? Based on your comment, it sounds like you have a multi-stage heat pump but I'd like to be 100% sure.

**Comment by pbros** [comment]
Hi, it's a 2 stage Gaz Furnace

**Comment by BigDogJonx** [comment]
Just to chime in here and provide some more data, the data shown on what the stage1 and stage2 runtimes (for say Cool) is in my opinion wrong.  Now its not your fault, its the way ecobee collects that data.  This mainly happens when Stage2 is running.  Youll notice there is time in both stage1 and stage2 column of ecobee data.  So when you look at your chart (say for me where it seems to show yesterday it ran for 9hrs on Stage1 and 3hrs on Stage2) its actually wrong.  Actual runtime on Stage1 is (Stage1-2) 6hrs and then Stage2 is 3hrs.  So total runtime is more like 9hrs, not 12hrs.

Again its the way ecobee reports it, it just assumed when stage2 is running, stage1 is also being called.  Im going to assume its the same for Heat (which I have stage1 and 2 heat).

Dixit

**Comment by ziebelje** [comment]
Yeah, I hear you. :)

I still need to verify that I've done this 100% correct, but I've got some bug fixes and some cleanup I'm hoping to deliver soon that should fix the over-reporting. See screenshot; top is the old way (graph hits 29 hours for a single day) and bottom is new way (graph hits 20 hours).

![image](https://user-images.githubusercontent.com/3288812/42662180-a4105e1a-85fe-11e8-872b-d7ba79d5bc77.png)

**Comment by BigDogJonx** [comment]
Nice.  On your example, your popup though still shows a total of 29hrs and seems like Cool1/2 flipped around in that popup.  Just pointing that out, but like you said you still working on it.

But out of curiosity, on this setup what is your run times?  Like do you really have 13-16hrs of Cool1 or 2 stage?

**Comment by ziebelje** [comment]
Actually I found some other systems in my database that had two-stage gas furnaces. @pbros, I'd still like to take a look specifically at yours if you are able but I'm going to close this one out as ready for the next release.

![image](https://user-images.githubusercontent.com/3288812/42732848-71f59234-87f6-11e8-9926-8ceb1180f1d9.png)

**Comment by BigDogJonx** [comment]
@ziebelje My new HVAC unit installed Aug 2017 is a 2stage Gas Heat and 2stage Cool.  So I believe it should have heat data if you wanted to take a look at mine.

**Comment by ziebelje** [comment]
I would feel a little bit better with some additional confirmation. Just message or post your serial number and I can pull up some data.

**Comment by BigDogJonx** [comment]
311027954554

**Comment by pbros** [comment]
Sent by e-mail

**Comment by ziebelje** [comment]
Sent you both screenshots to your emails. Thanks for the help!
